// <auto-generated />
using BookStore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookStore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191015061050_AlterBooksTableSeed")]
    partial class AlterBooksTableSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookStore.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUniqueName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Andrzej Sapkowski",
                            PhotoUniqueName = "3d4cdb83-8fb8-42aa-a05c-fb2f7d5d1e6d_wiedzmin-miecz-przeznaczenia.jpg",
                            Price = 28.99m,
                            Title = "Wiedźmin Miecz przeznaczenia"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Stanisław Lem",
                            PhotoUniqueName = "lem-kongres-futurologiczny.jpg",
                            Price = 18.89m,
                            Title = "Kongres futurologiczny"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Carl Gustav Jung",
                            PhotoUniqueName = "czerwona-ksiega.jpg",
                            Price = 87.99m,
                            Title = "Czerwona księga"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Richard King",
                            PhotoUniqueName = "dywizjon-303.jpg",
                            Price = 25.69m,
                            Title = "Dywizjon 303. Walka i codzienność"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Wojciech Drewniak",
                            PhotoUniqueName = "historia-bez-cenzury.jpg",
                            Price = 28.99m,
                            Title = "Historia bez cenzury 4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
